//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente.Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/", ConfigurationName="Service.Servicio")]
    public interface Servicio {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gamesoft.pucp.edu.pe/Servicio/modificarPokemonRequest", ReplyAction="http://services.gamesoft.pucp.edu.pe/Servicio/modificarPokemonResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Cliente.Service.modificarPokemonResponse modificarPokemon(Cliente.Service.modificarPokemonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gamesoft.pucp.edu.pe/Servicio/modificarPokemonRequest", ReplyAction="http://services.gamesoft.pucp.edu.pe/Servicio/modificarPokemonResponse")]
        System.Threading.Tasks.Task<Cliente.Service.modificarPokemonResponse> modificarPokemonAsync(Cliente.Service.modificarPokemonRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gamesoft.pucp.edu.pe/Servicio/listarTodosTiposRequest", ReplyAction="http://services.gamesoft.pucp.edu.pe/Servicio/listarTodosTiposResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Cliente.Service.listarTodosTiposResponse listarTodosTipos(Cliente.Service.listarTodosTiposRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gamesoft.pucp.edu.pe/Servicio/listarTodosTiposRequest", ReplyAction="http://services.gamesoft.pucp.edu.pe/Servicio/listarTodosTiposResponse")]
        System.Threading.Tasks.Task<Cliente.Service.listarTodosTiposResponse> listarTodosTiposAsync(Cliente.Service.listarTodosTiposRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gamesoft.pucp.edu.pe/Servicio/insertarPokemonRequest", ReplyAction="http://services.gamesoft.pucp.edu.pe/Servicio/insertarPokemonResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Cliente.Service.insertarPokemonResponse insertarPokemon(Cliente.Service.insertarPokemonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gamesoft.pucp.edu.pe/Servicio/insertarPokemonRequest", ReplyAction="http://services.gamesoft.pucp.edu.pe/Servicio/insertarPokemonResponse")]
        System.Threading.Tasks.Task<Cliente.Service.insertarPokemonResponse> insertarPokemonAsync(Cliente.Service.insertarPokemonRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gamesoft.pucp.edu.pe/Servicio/listarPokemonsRequest", ReplyAction="http://services.gamesoft.pucp.edu.pe/Servicio/listarPokemonsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Cliente.Service.listarPokemonsResponse listarPokemons(Cliente.Service.listarPokemonsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gamesoft.pucp.edu.pe/Servicio/listarPokemonsRequest", ReplyAction="http://services.gamesoft.pucp.edu.pe/Servicio/listarPokemonsResponse")]
        System.Threading.Tasks.Task<Cliente.Service.listarPokemonsResponse> listarPokemonsAsync(Cliente.Service.listarPokemonsRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gamesoft.pucp.edu.pe/Servicio/eliminarPokemonRequest", ReplyAction="http://services.gamesoft.pucp.edu.pe/Servicio/eliminarPokemonResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Cliente.Service.eliminarPokemonResponse eliminarPokemon(Cliente.Service.eliminarPokemonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gamesoft.pucp.edu.pe/Servicio/eliminarPokemonRequest", ReplyAction="http://services.gamesoft.pucp.edu.pe/Servicio/eliminarPokemonResponse")]
        System.Threading.Tasks.Task<Cliente.Service.eliminarPokemonResponse> eliminarPokemonAsync(Cliente.Service.eliminarPokemonRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gamesoft.pucp.edu.pe/Servicio/helloRequest", ReplyAction="http://services.gamesoft.pucp.edu.pe/Servicio/helloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Cliente.Service.helloResponse hello(Cliente.Service.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gamesoft.pucp.edu.pe/Servicio/helloRequest", ReplyAction="http://services.gamesoft.pucp.edu.pe/Servicio/helloResponse")]
        System.Threading.Tasks.Task<Cliente.Service.helloResponse> helloAsync(Cliente.Service.helloRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gamesoft.pucp.edu.pe/Servicio/listarTodasCategoriasRequest", ReplyAction="http://services.gamesoft.pucp.edu.pe/Servicio/listarTodasCategoriasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Cliente.Service.listarTodasCategoriasResponse listarTodasCategorias(Cliente.Service.listarTodasCategoriasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gamesoft.pucp.edu.pe/Servicio/listarTodasCategoriasRequest", ReplyAction="http://services.gamesoft.pucp.edu.pe/Servicio/listarTodasCategoriasResponse")]
        System.Threading.Tasks.Task<Cliente.Service.listarTodasCategoriasResponse> listarTodasCategoriasAsync(Cliente.Service.listarTodasCategoriasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gamesoft.pucp.edu.pe/Servicio/listarTodosRangosRequest", ReplyAction="http://services.gamesoft.pucp.edu.pe/Servicio/listarTodosRangosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Cliente.Service.listarTodosRangosResponse listarTodosRangos(Cliente.Service.listarTodosRangosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gamesoft.pucp.edu.pe/Servicio/listarTodosRangosRequest", ReplyAction="http://services.gamesoft.pucp.edu.pe/Servicio/listarTodosRangosResponse")]
        System.Threading.Tasks.Task<Cliente.Service.listarTodosRangosResponse> listarTodosRangosAsync(Cliente.Service.listarTodosRangosRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/")]
    public partial class pokemon : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string descriptionField;
        
        private double heightField;
        
        private int idPokemonField;
        
        private levelUpMove[] levelUpMovesField;
        
        private string nameField;
        
        private string nationalDexNumberField;
        
        private byte[] photoField;
        
        private type type1Field;
        
        private type type2Field;
        
        private double weightField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("height");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idPokemon {
            get {
                return this.idPokemonField;
            }
            set {
                this.idPokemonField = value;
                this.RaisePropertyChanged("idPokemon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("levelUpMoves", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public levelUpMove[] levelUpMoves {
            get {
                return this.levelUpMovesField;
            }
            set {
                this.levelUpMovesField = value;
                this.RaisePropertyChanged("levelUpMoves");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nationalDexNumber {
            get {
                return this.nationalDexNumberField;
            }
            set {
                this.nationalDexNumberField = value;
                this.RaisePropertyChanged("nationalDexNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=7)]
        public byte[] photo {
            get {
                return this.photoField;
            }
            set {
                this.photoField = value;
                this.RaisePropertyChanged("photo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public type type1 {
            get {
                return this.type1Field;
            }
            set {
                this.type1Field = value;
                this.RaisePropertyChanged("type1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public type type2 {
            get {
                return this.type2Field;
            }
            set {
                this.type2Field = value;
                this.RaisePropertyChanged("type2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public double weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
                this.RaisePropertyChanged("weight");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/")]
    public partial class levelUpMove : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int accuracyField;
        
        private int idLevelUpMoveField;
        
        private kind kindField;
        
        private int levelOfLearningField;
        
        private string moveNameField;
        
        private int powerField;
        
        private int powerPointField;
        
        private range rangeField;
        
        private type typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int accuracy {
            get {
                return this.accuracyField;
            }
            set {
                this.accuracyField = value;
                this.RaisePropertyChanged("accuracy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idLevelUpMove {
            get {
                return this.idLevelUpMoveField;
            }
            set {
                this.idLevelUpMoveField = value;
                this.RaisePropertyChanged("idLevelUpMove");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public kind kind {
            get {
                return this.kindField;
            }
            set {
                this.kindField = value;
                this.RaisePropertyChanged("kind");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int levelOfLearning {
            get {
                return this.levelOfLearningField;
            }
            set {
                this.levelOfLearningField = value;
                this.RaisePropertyChanged("levelOfLearning");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string moveName {
            get {
                return this.moveNameField;
            }
            set {
                this.moveNameField = value;
                this.RaisePropertyChanged("moveName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int power {
            get {
                return this.powerField;
            }
            set {
                this.powerField = value;
                this.RaisePropertyChanged("power");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int powerPoint {
            get {
                return this.powerPointField;
            }
            set {
                this.powerPointField = value;
                this.RaisePropertyChanged("powerPoint");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public range range {
            get {
                return this.rangeField;
            }
            set {
                this.rangeField = value;
                this.RaisePropertyChanged("range");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public type type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/")]
    public partial class kind : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idKindField;
        
        private string movementKindField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idKind {
            get {
                return this.idKindField;
            }
            set {
                this.idKindField = value;
                this.RaisePropertyChanged("idKind");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string movementKind {
            get {
                return this.movementKindField;
            }
            set {
                this.movementKindField = value;
                this.RaisePropertyChanged("movementKind");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/")]
    public partial class type : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int blueValueField;
        
        private int greenValueField;
        
        private int idTypeField;
        
        private string nameField;
        
        private int redValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int blueValue {
            get {
                return this.blueValueField;
            }
            set {
                this.blueValueField = value;
                this.RaisePropertyChanged("blueValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int greenValue {
            get {
                return this.greenValueField;
            }
            set {
                this.greenValueField = value;
                this.RaisePropertyChanged("greenValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idType {
            get {
                return this.idTypeField;
            }
            set {
                this.idTypeField = value;
                this.RaisePropertyChanged("idType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int redValue {
            get {
                return this.redValueField;
            }
            set {
                this.redValueField = value;
                this.RaisePropertyChanged("redValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/")]
    public partial class range : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idRangeField;
        
        private string movementRangeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idRange {
            get {
                return this.idRangeField;
            }
            set {
                this.idRangeField = value;
                this.RaisePropertyChanged("idRange");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string movementRange {
            get {
                return this.movementRangeField;
            }
            set {
                this.movementRangeField = value;
                this.RaisePropertyChanged("movementRange");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarPokemon", WrapperNamespace="http://services.gamesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarPokemonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Cliente.Service.pokemon pokemon;
        
        public modificarPokemonRequest() {
        }
        
        public modificarPokemonRequest(Cliente.Service.pokemon pokemon) {
            this.pokemon = pokemon;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarPokemonResponse", WrapperNamespace="http://services.gamesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarPokemonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarPokemonResponse() {
        }
        
        public modificarPokemonResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosTipos", WrapperNamespace="http://services.gamesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosTiposRequest {
        
        public listarTodosTiposRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosTiposResponse", WrapperNamespace="http://services.gamesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosTiposResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Cliente.Service.type[] @return;
        
        public listarTodosTiposResponse() {
        }
        
        public listarTodosTiposResponse(Cliente.Service.type[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPokemon", WrapperNamespace="http://services.gamesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarPokemonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Cliente.Service.pokemon pokemon;
        
        public insertarPokemonRequest() {
        }
        
        public insertarPokemonRequest(Cliente.Service.pokemon pokemon) {
            this.pokemon = pokemon;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPokemonResponse", WrapperNamespace="http://services.gamesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarPokemonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarPokemonResponse() {
        }
        
        public insertarPokemonResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPokemons", WrapperNamespace="http://services.gamesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPokemonsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public listarPokemonsRequest() {
        }
        
        public listarPokemonsRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPokemonsResponse", WrapperNamespace="http://services.gamesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPokemonsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Cliente.Service.pokemon[] @return;
        
        public listarPokemonsResponse() {
        }
        
        public listarPokemonsResponse(Cliente.Service.pokemon[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPokemon", WrapperNamespace="http://services.gamesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarPokemonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPokemon;
        
        public eliminarPokemonRequest() {
        }
        
        public eliminarPokemonRequest(int idPokemon) {
            this.idPokemon = idPokemon;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPokemonResponse", WrapperNamespace="http://services.gamesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarPokemonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarPokemonResponse() {
        }
        
        public eliminarPokemonResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hello", WrapperNamespace="http://services.gamesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public helloRequest() {
        }
        
        public helloRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloResponse", WrapperNamespace="http://services.gamesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public helloResponse() {
        }
        
        public helloResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodasCategorias", WrapperNamespace="http://services.gamesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodasCategoriasRequest {
        
        public listarTodasCategoriasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodasCategoriasResponse", WrapperNamespace="http://services.gamesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodasCategoriasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Cliente.Service.kind[] @return;
        
        public listarTodasCategoriasResponse() {
        }
        
        public listarTodasCategoriasResponse(Cliente.Service.kind[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosRangos", WrapperNamespace="http://services.gamesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosRangosRequest {
        
        public listarTodosRangosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosRangosResponse", WrapperNamespace="http://services.gamesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosRangosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Cliente.Service.range[] @return;
        
        public listarTodosRangosResponse() {
        }
        
        public listarTodosRangosResponse(Cliente.Service.range[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioChannel : Cliente.Service.Servicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioClient : System.ServiceModel.ClientBase<Cliente.Service.Servicio>, Cliente.Service.Servicio {
        
        public ServicioClient() {
        }
        
        public ServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente.Service.modificarPokemonResponse Cliente.Service.Servicio.modificarPokemon(Cliente.Service.modificarPokemonRequest request) {
            return base.Channel.modificarPokemon(request);
        }
        
        public int modificarPokemon(Cliente.Service.pokemon pokemon) {
            Cliente.Service.modificarPokemonRequest inValue = new Cliente.Service.modificarPokemonRequest();
            inValue.pokemon = pokemon;
            Cliente.Service.modificarPokemonResponse retVal = ((Cliente.Service.Servicio)(this)).modificarPokemon(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente.Service.modificarPokemonResponse> Cliente.Service.Servicio.modificarPokemonAsync(Cliente.Service.modificarPokemonRequest request) {
            return base.Channel.modificarPokemonAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente.Service.modificarPokemonResponse> modificarPokemonAsync(Cliente.Service.pokemon pokemon) {
            Cliente.Service.modificarPokemonRequest inValue = new Cliente.Service.modificarPokemonRequest();
            inValue.pokemon = pokemon;
            return ((Cliente.Service.Servicio)(this)).modificarPokemonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente.Service.listarTodosTiposResponse Cliente.Service.Servicio.listarTodosTipos(Cliente.Service.listarTodosTiposRequest request) {
            return base.Channel.listarTodosTipos(request);
        }
        
        public Cliente.Service.type[] listarTodosTipos() {
            Cliente.Service.listarTodosTiposRequest inValue = new Cliente.Service.listarTodosTiposRequest();
            Cliente.Service.listarTodosTiposResponse retVal = ((Cliente.Service.Servicio)(this)).listarTodosTipos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente.Service.listarTodosTiposResponse> Cliente.Service.Servicio.listarTodosTiposAsync(Cliente.Service.listarTodosTiposRequest request) {
            return base.Channel.listarTodosTiposAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente.Service.listarTodosTiposResponse> listarTodosTiposAsync() {
            Cliente.Service.listarTodosTiposRequest inValue = new Cliente.Service.listarTodosTiposRequest();
            return ((Cliente.Service.Servicio)(this)).listarTodosTiposAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente.Service.insertarPokemonResponse Cliente.Service.Servicio.insertarPokemon(Cliente.Service.insertarPokemonRequest request) {
            return base.Channel.insertarPokemon(request);
        }
        
        public int insertarPokemon(Cliente.Service.pokemon pokemon) {
            Cliente.Service.insertarPokemonRequest inValue = new Cliente.Service.insertarPokemonRequest();
            inValue.pokemon = pokemon;
            Cliente.Service.insertarPokemonResponse retVal = ((Cliente.Service.Servicio)(this)).insertarPokemon(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente.Service.insertarPokemonResponse> Cliente.Service.Servicio.insertarPokemonAsync(Cliente.Service.insertarPokemonRequest request) {
            return base.Channel.insertarPokemonAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente.Service.insertarPokemonResponse> insertarPokemonAsync(Cliente.Service.pokemon pokemon) {
            Cliente.Service.insertarPokemonRequest inValue = new Cliente.Service.insertarPokemonRequest();
            inValue.pokemon = pokemon;
            return ((Cliente.Service.Servicio)(this)).insertarPokemonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente.Service.listarPokemonsResponse Cliente.Service.Servicio.listarPokemons(Cliente.Service.listarPokemonsRequest request) {
            return base.Channel.listarPokemons(request);
        }
        
        public Cliente.Service.pokemon[] listarPokemons(string name) {
            Cliente.Service.listarPokemonsRequest inValue = new Cliente.Service.listarPokemonsRequest();
            inValue.name = name;
            Cliente.Service.listarPokemonsResponse retVal = ((Cliente.Service.Servicio)(this)).listarPokemons(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente.Service.listarPokemonsResponse> Cliente.Service.Servicio.listarPokemonsAsync(Cliente.Service.listarPokemonsRequest request) {
            return base.Channel.listarPokemonsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente.Service.listarPokemonsResponse> listarPokemonsAsync(string name) {
            Cliente.Service.listarPokemonsRequest inValue = new Cliente.Service.listarPokemonsRequest();
            inValue.name = name;
            return ((Cliente.Service.Servicio)(this)).listarPokemonsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente.Service.eliminarPokemonResponse Cliente.Service.Servicio.eliminarPokemon(Cliente.Service.eliminarPokemonRequest request) {
            return base.Channel.eliminarPokemon(request);
        }
        
        public int eliminarPokemon(int idPokemon) {
            Cliente.Service.eliminarPokemonRequest inValue = new Cliente.Service.eliminarPokemonRequest();
            inValue.idPokemon = idPokemon;
            Cliente.Service.eliminarPokemonResponse retVal = ((Cliente.Service.Servicio)(this)).eliminarPokemon(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente.Service.eliminarPokemonResponse> Cliente.Service.Servicio.eliminarPokemonAsync(Cliente.Service.eliminarPokemonRequest request) {
            return base.Channel.eliminarPokemonAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente.Service.eliminarPokemonResponse> eliminarPokemonAsync(int idPokemon) {
            Cliente.Service.eliminarPokemonRequest inValue = new Cliente.Service.eliminarPokemonRequest();
            inValue.idPokemon = idPokemon;
            return ((Cliente.Service.Servicio)(this)).eliminarPokemonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente.Service.helloResponse Cliente.Service.Servicio.hello(Cliente.Service.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            Cliente.Service.helloRequest inValue = new Cliente.Service.helloRequest();
            inValue.name = name;
            Cliente.Service.helloResponse retVal = ((Cliente.Service.Servicio)(this)).hello(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente.Service.helloResponse> Cliente.Service.Servicio.helloAsync(Cliente.Service.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente.Service.helloResponse> helloAsync(string name) {
            Cliente.Service.helloRequest inValue = new Cliente.Service.helloRequest();
            inValue.name = name;
            return ((Cliente.Service.Servicio)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente.Service.listarTodasCategoriasResponse Cliente.Service.Servicio.listarTodasCategorias(Cliente.Service.listarTodasCategoriasRequest request) {
            return base.Channel.listarTodasCategorias(request);
        }
        
        public Cliente.Service.kind[] listarTodasCategorias() {
            Cliente.Service.listarTodasCategoriasRequest inValue = new Cliente.Service.listarTodasCategoriasRequest();
            Cliente.Service.listarTodasCategoriasResponse retVal = ((Cliente.Service.Servicio)(this)).listarTodasCategorias(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente.Service.listarTodasCategoriasResponse> Cliente.Service.Servicio.listarTodasCategoriasAsync(Cliente.Service.listarTodasCategoriasRequest request) {
            return base.Channel.listarTodasCategoriasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente.Service.listarTodasCategoriasResponse> listarTodasCategoriasAsync() {
            Cliente.Service.listarTodasCategoriasRequest inValue = new Cliente.Service.listarTodasCategoriasRequest();
            return ((Cliente.Service.Servicio)(this)).listarTodasCategoriasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente.Service.listarTodosRangosResponse Cliente.Service.Servicio.listarTodosRangos(Cliente.Service.listarTodosRangosRequest request) {
            return base.Channel.listarTodosRangos(request);
        }
        
        public Cliente.Service.range[] listarTodosRangos() {
            Cliente.Service.listarTodosRangosRequest inValue = new Cliente.Service.listarTodosRangosRequest();
            Cliente.Service.listarTodosRangosResponse retVal = ((Cliente.Service.Servicio)(this)).listarTodosRangos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente.Service.listarTodosRangosResponse> Cliente.Service.Servicio.listarTodosRangosAsync(Cliente.Service.listarTodosRangosRequest request) {
            return base.Channel.listarTodosRangosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente.Service.listarTodosRangosResponse> listarTodosRangosAsync() {
            Cliente.Service.listarTodosRangosRequest inValue = new Cliente.Service.listarTodosRangosRequest();
            return ((Cliente.Service.Servicio)(this)).listarTodosRangosAsync(inValue);
        }
    }
}
